### ISSUE TITLE
So i started my Server and that issue Occured!

### ISSUE THREAD

**Issue by Blunatix** [RootsTeam/AdventureBags#10]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  OpenEyePlugin (OpenEye-1.12.2-0.8.jar)
  llibrary (llibrary-core-1.0.8-1.12.2.jar)
Contact their authors BEFORE contacting forge

// Oh - I know what I did wrong!

Time: 10/27/18 8:10 PM
Description: Exception in server tick loop

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Adventure Bags (adventurebags)
Caused by: java.lang.NoClassDefFoundError: net/minecraft/client/settings/KeyBinding
	at sirshadow.adventurebags.common.utils.handler.KeyBindings.<init>(KeyBindings.java:18)
	at sirshadow.adventurebags.common.utils.handler.KeyBindings.<clinit>(KeyBindings.java:12)
	at sirshadow.adventurebags.proxys.CommonProxy.registerKeybinds(CommonProxy.java:56)
	at sirshadow.adventurebags.proxys.CommonProxy.preInit(CommonProxy.java:32)
	at sirshadow.adventurebags.proxys.ServerProxy.preInit(ServerProxy.java:14)
	at sirshadow.adventurebags.AdventureBags.preInit(AdventureBags.java:30)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:627)
	at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:218)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:196)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:135)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:627)
	at net.minecraftforge.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:99)
	at net.minecraftforge.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:332)
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:125)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: net.minecraft.client.settings.KeyBinding
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 41 more
Caused by: net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerException: Exception in class transformer net.minecraftforge.fml.common.asm.transformers.SideTransformer@41a6d121 from coremod FMLCorePlugin
	at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.transform(ASMTransformerWrapper.java:260)
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176)
	... 43 more
Caused by: java.lang.RuntimeException: Attempted to load class bhy for invalid side SERVER
	at net.minecraftforge.fml.common.asm.transformers.SideTransformer.transform(SideTransformer.java:62)
	at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.transform(ASMTransformerWrapper.java:256)
	... 45 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Linux (amd64) version 4.4.26-nitradoV3-MC-1000-nH-dP-d-a
	Java Version: 1.8.0_151, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1003045832 bytes (956 MB) / 1292894208 bytes (1233 MB) up to 2863661056 bytes (2731 MB)
	JVM Flags: 2 total; -Xms256M -Xmx3072M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.4.2745 41 mods loaded, 41 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID             | Version           | Source                                        | Signature                                |
	|:----- |:-------------- |:----------------- |:--------------------------------------------- |:---------------------------------------- |
	| UCH   | minecraft      | 1.12.2            | minecraft.jar                                 | None                                     |
	| UCH   | mcp            | 9.42              | minecraft.jar                                 | None                                     |
	| UCH   | FML            | 8.0.99.99         | minecraft_server.jar                          | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCH   | forge          | 14.23.4.2745      | minecraft_server.jar                          | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCH   | OpenEye        | 0.8               | OpenEye-1.12.2-0.8.jar                        | None                                     |
	| UCEE  | adventurebags  | 0.9               | ab-1.12.2-0.9r.jar                            | None                                     |
	| UC    | aquaculture    | 1.6.1             | Aquaculture-Mod-1.12.2.jar                    | None                                     |
	| UC    | battletowers   | 1.6.1             | BattleTowers-Mod-1.12.2.jar                   | None                                     |
	| UC    | baubles        | 1.5.2             | Baubles-1.12-1.5.2.jar                        | None                                     |
	| UC    | bibliocraft    | 2.4.5             | BiblioCraft-Mod-1.12.2.jar                    | None                                     |
	| UC    | biomesoplenty  | 7.0.1.2361        | BiomesOPlenty-1.12.2-7.0.1.2361-universal.jar | None                                     |
	| UC    | bookshelf      | 2.3.553           | Bookshelf-1.12.2-2.3.553.jar                  | d476d1b22b218a10d845928d1665d45fce301b27 |
	| UC    | chococraft     | 0.9.1.52          | ChocoCraft-Mod-1.12.1.jar                     | None                                     |
	| UC    | codechickenlib | 3.2.2.353         | CodeChickenLib-1.12.2.jar                     | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UC    | cucumber       | 1.1.1             | Cucumber-1.12.2-1.1.1.jar                     | None                                     |
	| UC    | customspawner  | 3.11.4            | Custom-Mob-Spawner-Mod-1.12.2.jar             | None                                     |
	| UC    | dimdoors       | 3.0.0-beta4       | Dimensional-Doors-Mod-1.12.2.jar              | None                                     |
	| UC    | dldungeonsjdg  | 1.9.3             | Doomlike-Dungeons-Mod-1.12.2.jar              | None                                     |
	| UC    | eplus          | 5.0.163           | Enchanting-Plus-Mod-1.12.2.jar                | d476d1b22b218a10d845928d1665d45fce301b27 |
	| UC    | gravestone     | 1.10.2            | gravestone-1.10.2.jar                         | None                                     |
	| UC    | placebo        | 1.4.1             | Placebo-1.12.2.jar                            | None                                     |
	| UC    | hexxitgear     | 2.7.0             | Hexxit+Gear-1.12.2-2.7.0.jar                  | None                                     |
	| UC    | llibrary       | 1.7.15            | LLibrary-1.12.2.jar                           | b9f30a813bee3b9dd5652c460310cfcd54f6b7ec |
	| UC    | iceandfire     | 1.3.1             | Ice-and-Fire-Mod-1.12.2.jar                   | None                                     |
	| UC    | ichunutil      | 7.0.2             | iChunUtil-1.12.2-7.0.2.jar                    | None                                     |
	| UC    | infernalmobs   | 1.7.3             | Infernal-Mobs-Mod-1.12.2.jar                  | None                                     |
	| UC    | infinitylib    | 1.12.2-1.12.0     | InfinityLib-1.12.2.jar                        | None                                     |
	| UC    | ironchest      | 1.12.2-7.0.46.831 | Iron-Chests-Mod-1.12.2.jar                    | None                                     |
	| UC    | lootbags       | 2.5.7             | LootBags-1.12.2-2.5.7.jar                     | None                                     |
	| UC    | mantle         | 1.12-1.3.2.24     | Mantle-1.12-1.3.2.24.jar                      | None                                     |
	| UC    | mocreatures    | 12.0.5            | Mo-Creatures-Mod-1.12.2.jar                   | None                                     |
	| UC    | morpheus       | 1.12-3.3.2        | Morpheus-1.12-3.3.2.jar                       | None                                     |
	| UC    | ptrmodellib    | 1.0.2             | PTRLib-1.0.2.jar                              | None                                     |
	| UC    | xreliquary     | 1.12.2-1.3.4.747  | Reliquary-1.12.2-1.3.4.747.jar                | None                                     |
	| UC    | roguelike      | 1.7.2             | RoguelikeDungeons-1.12.2-1.7.2.jar            | None                                     |
	| UC    | secretroomsmod | 5.3.2             | secretroomsmod-1.12.2-5.3.2.jar               | None                                     |
	| UC    | thaumcraft     | 6.1.BETA24        | Thaumcraft-Mod-1.12.2.jar                     | None                                     |
	| UC    | bspkrscore     | at_0.9            | TreeCapitator-Mod-1.12.jar                    | None                                     |
	| UC    | treecapitator  | at_0.9            | TreeCapitator-Mod-1.12.jar                    | None                                     |
	| UC    | twilightforest | 3.7.424           | twilightforest-1.12.2-3.7.424-universal.jar   | None                                     |
	| UC    | wawla          | 2.5.246           | Wawla-1.12.2-2.5.246.jar                      | d476d1b22b218a10d845928d1665d45fce301b27 |

	Loaded coremods (and transformers): 
OpenEyePlugin (OpenEye-1.12.2-0.8.jar)
  openeye.asm.MultiTransformer
llibrary (llibrary-core-1.0.8-1.12.2.jar)
  net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
  net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
	Profiler Position: N/A (disabled)
	Is Modded: Definitely; Server brand changed to 'fml,forge'
	Type: Dedicated Server (map_server.txt)

**Comment by TilenOkretic** [comment]
Should be fixed in version 9.1

**Comment by ShadowGamerXY** [comment]
Use the beta version the problem should be fixed.
