### ISSUE TITLE
Server Crash Issue 1.12.2

### ISSUE THREAD

**Issue by DaemonUmbra** [RootsTeam/AdventureBags#7]
This is a different error to #6 but the cause is the same, the mod is attempting to access Client-Only code from the "Server" or "Common" side. This error was from the code currently in the repo (commit hash: [22b59c84b8dc41a204e8ddd944aea731f60d6970](https://github.com/ShadowGamerXY/AdventureBags/tree/22b59c84b8dc41a204e8ddd944aea731f60d6970)).

Caused by: java.lang.NoClassDefFoundError: net/minecraft/client/entity/EntityPlayerSP
	at java.lang.Class.getDeclaredConstructors0(Native Method) ~[?:1.8.0_152]
	at java.lang.Class.privateGetDeclaredConstructors(Class.java:2671) ~[?:1.8.0_152]
	at java.lang.Class.getConstructor0(Class.java:3075) ~[?:1.8.0_152]
	at java.lang.Class.newInstance(Class.java:412) ~[?:1.8.0_152]
	at net.minecraftforge.fml.common.network.simpleimpl.SimpleNetworkWrapper.instantiate(SimpleNetworkWrapper.java:171) ~[forgeSrc-1.12-14.21.0.2373.jar:?]
	at net.minecraftforge.fml.common.network.simpleimpl.SimpleNetworkWrapper.registerMessage(SimpleNetworkWrapper.java:164) ~[forgeSrc-1.12-14.21.0.2373.jar:?]
	at **sirshadow.adventurebags.common.network.PacketHandler.register(PacketHandler.java:18)** ~[bin/:?]
	at sirshadow.adventurebags.proxys.CommonProxy.preInit(CommonProxy.java:33) ~[bin/:?]
	at sirshadow.adventurebags.proxys.ServerProxy.preInit(ServerProxy.java:14) ~[bin/:?]
	at sirshadow.adventurebags.AdventureBags.preInit(AdventureBags.java:29) ~[bin/:?]

**Comment by ShadowGamerXY** [comment]
Should be fixed in 0.8 update.
